name: Scan external links for errors

on:
  schedule:
    - cron: 0 8 * * *
  workflow_dispatch:

jobs:
  scan:
    name: Check with linkinator
    runs-on: ubuntu-latest
    steps:
      - name: linkinator
        id: linkinator
      # status: 0 means that we have been blocked by their firewall/cloudflare etc
        run: | npx linkinator --format=json --redirects=error https://bringbackourneighbours.de/internal-check-links/ |  jq '.links[] | select(.state =="BROKEN" and .status != 0)') >> $GITHUB_OUTPUT
      - name: outcheck
        id: check
        if: {{steps.linkinator.outputs.brokenlinks != ''}}
        run: | exit 1
