name: Scan external links for errors

on:
  schedule:
    - cron: 0 8 * * *
  workflow_dispatch:

jobs:
  scan:
    name: Check with linkinator
    runs-on: ubuntu-latest
    steps:
      - run: npx linkinator --format=json --redirects=error https://bringbackourneighbours.de/internal-check-links/ |  jq '.links[] | select(.state =="BROKEN")'
