name: Scan external links for errors

on:
  schedule:
    - cron: 0 8 * * *
  workflow_dispatch:

jobs:
  scan:
    name: Check with linkinator
    runs-on: ubuntu-latest
    steps:
      - name: linkinator
        id: linkinator
      # status: 0 means that we have been blocked by their firewall/cloudflare etc
        run: BROKEN_LINKS=$(npx linkinator --format=json --redirects=error https://bringbackourneighbours.de/internal-check-links/ |  jq '.links[] | select(.state =="BROKEN" and .status != 0)')
      - name: tovar
        id: tovar
        run: echo $BROKEN_LINKS >> $GITHUB_OUTPUT
      - name: outcheck
        id: check
        if: ${{steps.tovar.outputs.brokenlinks != ''}}
        run: exit 1
